set(CMAKE_SYSTEM_NAME    Windows)
set(CMAKE_SYSTEM_VERSION 10)

set(LLVM_MINGW_PREFIX x86_64-w64-mingw32)
set(LLVM_MINGW_PATH   /opt/llvm-mingw/bin)

set(CMAKE_C_COMPILER   ${LLVM_MINGW_PATH}/${LLVM_MINGW_PREFIX}-clang)
set(CMAKE_CXX_COMPILER ${LLVM_MINGW_PATH}/${LLVM_MINGW_PREFIX}-clang++)
set(CMAKE_RC_COMPILER  ${LLVM_MINGW_PATH}/${LLVM_MINGW_PREFIX}-windres)

set(CMAKE_FIND_ROOT_PATH /opt/llvm-mingw/${LLVM_MINGW_PREFIX})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
